# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('first_favorite', models.PositiveSmallIntegerField()),
                ('second_favorite', models.PositiveSmallIntegerField()),
                ('third_favorite', models.PositiveSmallIntegerField()),
                ('fourth_favorite', models.PositiveSmallIntegerField()),
                ('fifth_favorite', models.PositiveSmallIntegerField()),
                ('power_ball_number', models.PositiveSmallIntegerField(verbose_name='Powerball')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PopularSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_most_popular', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
